##################################################
# Name: linter.yaml
# Description: Workflow for the GitHub Super Linter
#
# NOTES:
#       Reference: https://github.com/github/super-linter
#
##################################################

name: Linter

on:
  push:
    branches-ignore:
      - $default-branch

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: GitHub Super Linter

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository with all history and tags
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-depth: 0
          submodules: false
          clean: true
          persist-credentials: true

      - id: run_linter
        name: Run GitHub Super Linter
        uses: github/super-linter@v3
        env:
          # Enable the linter types based on your project
          DISABLE_ERRORS: false
          DEFAULT_BRANCH: $default-branch
          ACTIONS_RUNNER_DEBUG: false
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          ANSIBLE_DIRECTORY: "/ansible"
          VALIDATE_BASH: false
          VALIDATE_COFFEE: false
          VALIDATE_DOCKER: false
          VALIDATE_GO: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSON: false
          VALIDATE_KOTLIN: false
          VALIDATE_MD: true
          VALIDATE_PERL: false
          VALIDATE_POWERSHELL: false
          VALIDATE_PYTHON: false
          VALIDATE_RUBY: false
          VALIDATE_TERRAFORM: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_XML: false
          VALIDATE_YAML: false
